### ISSUE TITLE
Send sms for today modification

### ISSUE THREAD

**Issue by nobe4** [nobe4/extralendar#10]

**Comment by malcolm282** [comment]
In my opinion, it's not free to send SMS. So maybe only e-mails?

**Comment by nobe4** [comment]
google can do it for "free", the idea is to create a event with a sms reminder for now, wait ~5 minutes and remove it, it will do the job.
The option will be only available for the ones who accept to get sms notifications from google ...

**Comment by malcolm282** [comment]
In france:
Recevoir des SMS via Google Chat dans Gmail

Depuis le 1er avril 2014, il n'est plus possible d'envoyer des SMS à des contacts téléphoniques via le chat de Gmail. Tous les opérateurs mobiles sont concernés.
Means it's no more possible.

**Comment by nobe4** [comment]
The hangout (gmail chat) is not the point here, sms notifications are sent by google for a registered number only when you activate the option for your events.
https://support.google.com/calendar/answer/45351?hl=en

**Comment by malcolm282** [comment]
Yes, but one point:
If the script remove and create then a new calendar, you will be notified every X times, no?

**Comment by nobe4** [comment]
yes, I didn't though about it, the option is only for new events for the current day, so hopefully no more than one time a day...
