### ISSUE TITLE
Impossible de voir à +2 semaines

### ISSUE THREAD

**Issue by malcolm282** [nobe4/extralendar#15]
Il est impossible de voir sur plus de deux semaines... C'est possible de changer et de passer à une vision largement plus importante (1-2 mois)?

Cordialement,

**Comment by nobe4** [comment]
oui, modifier le step avec le nombre de jours souhaité, après si les données ne sont pas là c'est peut être un problème d'extranet qui n'est pas encore planifié à ce jour...

**Comment by malcolm282** [comment]
Les infos sont là, mais je peux pas modifier le nombre de step, si?

**Comment by nobe4** [comment]
https://github.com/nobe4/extralendar/wiki/Basic-Setup#optional-variables : step

**Comment by malcolm282** [comment]
Ca marche, mais va falloir mettre des exemples sur le Wiki.
En tout cas, merci pour la rapidité !
