### ISSUE TITLE
Error Message : Impossible to fetch the ASP id, check the ADDRESS

### ISSUE THREAD

**Issue by GreG28** [nobe4/extralendar#16]
J'ai ce message d'erreur dans le l'affichage du script execution..

[14-10-01 12:23:21:110 CEST] MailApp.sendEmail([gregoire.fouillard@efrei.net, Error report Extralendar, 
Date: Wed Oct 01 2014 12:23:21 GMT+0200 (CEST)
Number: 10004
Message: Impossible to fetch the ASP id, check the ADDRESS

**Comment by nobe4** [comment]
does the first entry in : https://github.com/nobe4/extralendar/wiki/FAQ solve the problem ?

**Comment by GreG28** [comment]
Yep ! It does... I'm fool.. ^^
