### ISSUE TITLE
Step+1 day gets duplicate events

### ISSUE THREAD

**Issue by ludovicmnji** [nobe4/extralendar#17]
Salut,

Déjà merci d'avoir créé ce script ça change la vie ! 

J'ai relevé un bug assez pénible : certains cours s'ajoutent à chaque synchronisation. Ca ne le fait que sur certains mais du coup on peut arriver à avoir 10 événements dupliqués en 1 journée si on ne les supprime pas au fur et à mesure.

C'est pas très grave mais bon ça peut être gênant à la longue ;)

![capture d ecran 2014-10-01 a 13 57 01](https://cloud.githubusercontent.com/assets/6171841/4474646/99a9de06-4962-11e4-8d28-ecbe23cd06f2.png)

**Comment by nobe4** [comment]
yep, we know this bug, we are working on it !
