### ISSUE TITLE
Issue with the hours

### ISSUE THREAD

**Issue by gokender** [nobe4/extralendar#18]
Hi guys,

First thank you for the script, it's very usefull.

I've noticed an issue with the hours in the calendar. As you can see from the image below, there is a shift between the google calendar and the extranet (exactly +9 hours). 

![emploi du temps](https://cloud.githubusercontent.com/assets/3709740/4721280/b7bcce6e-5937-11e4-803c-d947307274ba.PNG)

I just want to know if I'm the only one whit this problem.

Thanks again

**Comment by JohnMichaelTO** [comment]
Just make sure that your time zone is GMT+1 (Paris).

**Comment by nobe4** [comment]
The hour we send to the google calendar isn't moved at all : https://github.com/nobe4/extralendar/blob/master/core.gs#L251

So you should set the time zone on your google calendar.

**Comment by gokender** [comment]
Yep, it's the first thing that I checked before asking you and my time zone is Paris

**Comment by JohnMichaelTO** [comment]
Did you check the time zone of the calendar too ?
Because you might have the time zone in general, and the time zone for one specific calendar.

**Comment by gokender** [comment]
Yes, it's the good time zone in the calendar and general settings

**Comment by nobe4** [comment]
Where did you create your gmail account ? A friend had the same issue but he created his account in the USA...
