### ISSUE TITLE
I received an email warning me about a bug, and there is no more event after today in my calendar.

### ISSUE THREAD

**Issue by matthieudelaro** [nobe4/extralendar#19]
The reason seems to be the following : Event which is an error, not an event, and therefore can't be added to the calendar.

Initial email report :
Date: Tue Dec 16 2014 18:38:17 GMT+0100 (CET)
Number: undefined
Message: Cannot call method "match" of undefined.
Line: 131 (which is var d = title.match(new RegExp(regexp));, in parseTitle(title) function, called by createEvent(calendar, event) function)

So I changed the source code, and it turns out that this is called at least for the first event in my calendar (the script won't go further), and that the event processed by createEvent() seems to be an error log or alert box message, instead of an event : 
{  
    \"title\":\"Erreur\",
    \"buttons\":Ext.Msg.OK,
    \"closable\":false,
    \"icon\":Ext.Msg.ERROR,
    \"msg\":    \"An error occurred (16/12/2014 19:01:11    ) while processing your request. Please contact the administrator.\"
}

I've set createEvent function to this code : 

``` javascript
var numberOfEvents = 0;
// Create Event
function createEvent(calendar, event) {
  numberOfEvents++;
  try {
    var info = parseTitle(event.title);

    var title = info.title;
    var start = new Date(getDateFromIso(event.start));
    var end = new Date(getDateFromIso(event.end));
    var desc = info.teacher;
    var loc = info.location;

    if(args.log_update){
      desc += "\n\nUpdated at :\n" + new Date();
    }

    var event = calendar.createEvent(title, start, end, {
      description : desc,
      location : loc
    });
  } catch (e) {
    mailError(e);
    mailError(new Error("Could not handle event number "+numberOfEvents+" : " + JSON.stringify(event)));
  }
};
```

and I get the following email :
Date: Tue Dec 16 2014 19:01:12 GMT+0100 (CET)
Number: undefined
Message: Could not handle event number 1 : "Ext.Msg.show({\"title\":\"Erreur\",\"buttons\":Ext.Msg.OK,\"closable\":false,\"icon\":Ext.Msg.ERROR,\"msg\":\"An error occurred (16/12/2014 19:01:11) while processing your request. Please contact the administrator.\"});"
Line: 0

**Comment by nobe4** [comment]
It seems that your issue is generated by the new extranet system, solved with 1c8e7d83dbcbd2c9d136662b9b6e914c57a5457e 

The new version will be pushed to master soon.

**Comment by matthieudelaro** [comment]
Works again. Thanks a lot !

**Comment by matthieudelaro** [comment]
Merci beaucoup !
