### ISSUE TITLE
Problem parsing hours

### ISSUE THREAD

**Issue by Chimaytric** [nobe4/extralendar#5]
When the script parsed the timetable, he began the workdays around 6PM.
![bug](https://cloud.githubusercontent.com/assets/1206531/4356597/e8a3be64-425a-11e4-916b-c974c2c7872f.png)

**Comment by nobe4** [comment]
can i have a log ? set the LOG_LEVEL to 3 and cp/paste it :)
(to access it : ctrl + enter)

**Comment by Bindless-Chicken** [comment]
Have you managed to fix your issue ?
